
DROP TABLE IF EXISTS PLAYERS;

CREATE TABLE PLAYERS (
    PLAYERID VARCHAR(20) PRIMARY KEY,
    BIRTHYEAR INT,
    BIRTHMONTH INT,
    BIRTHDAY INT,
    BIRTHCOUNTRY VARCHAR(50),
    BIRTHSTATE VARCHAR(50),
    BIRTHCITY VARCHAR(50),
    DEATHYEAR INT,
    DEATHMONTH INT,
    DEATHDAY INT,
    DEATHCOUNTRY VARCHAR(50),
    DEATHSTATE VARCHAR(50),
    DEATHCITY VARCHAR(50),
    NAMEFIRST VARCHAR(50),
    NAMELAST VARCHAR(50),
    NAMEGIVEN VARCHAR(100),
    WEIGHT FLOAT,
    HEIGHT FLOAT,
    BATS VARCHAR(2),
    THROWS VARCHAR(2),
    DEBUT DATE,
    FINALGAME DATE,
    RETROID VARCHAR(20),
    BBREFID VARCHAR(20)
);

INSERT INTO PLAYERS (
    PLAYERID, BIRTHYEAR, BIRTHMONTH, BIRTHDAY, BIRTHCOUNTRY, BIRTHSTATE, BIRTHCITY,
    DEATHYEAR, DEATHMONTH, DEATHDAY, DEATHCOUNTRY, DEATHSTATE, DEATHCITY,
    NAMEFIRST, NAMELAST, NAMEGIVEN, WEIGHT, HEIGHT, BATS, THROWS, DEBUT, FINALGAME, RETROID, BBREFID
) SELECT 
    playerID, birthYear, birthMonth, birthDay, birthCountry, birthState, birthCity,
    deathYear, deathMonth, deathDay, deathCountry, deathState, deathCity,
    nameFirst, nameLast, nameGiven, weight, height, bats, throws, debut, finalGame, retroID, bbrefID
FROM CSVREAD('classpath:Player.csv');

CREATE INDEX IF NOT EXISTS idx_player_id ON PLAYERS (PLAYERID);
CREATE INDEX IF NOT EXISTS idx_birth_country ON PLAYERS (BIRTHCOUNTRY);