apiVersion: v1
kind: Service
metadata:
  name: a4a-model
spec:
  type: NodePort
  selector:
    app: a4a-model
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30002
